debug_build:
  stage: build
  script:
    - pwd
    - 'msbuild -t:build /p:Configuration=MQ2DotNet-Debug -restore -p:RestorePackagesPath=build/Debug/packages'
  artifacts:
    paths:
    - build/Debug/MQ2DotNet
  only:
    - develop

release_build:
  stage: build
  script:
    - 'msbuild -t:build /p:Configuration=MQ2DotNet-Release -restore -p:RestorePackagesPath=build/Release/packages'
  artifacts:
    paths:
    - build/Release/MQ2DotNet
  only:
    - tags

release_deploy:
  stage: deploy
  script:
    - 'Compress-Archive -Path build/Debug/MQ2DotNet/MQ2DotNet.dll, build/Debug/MQ2DotNet/MQ2DotNet.xml -CompressionLevel Optimal -DestinationPath build/Debug/MQ2DotNet.zip
    - '$response = (wsl curl --request POST --header "Private-Token: $($env:GITLAB_API_KEY)" --form "file=@build/Debug/MQ2DotNet.zip" https://gitlab.com/api/v4/projects/7242930/uploads)'
    - '$fileUrl = "https://gitlab.com/alynel/MQ2DotNet$(($response | ConvertFrom-Json).url)"'
    - '$data = @{ "name"=$env:CI_COMMIT_TAG; "tag_name":$env:CI_COMMIT_TAG; "description"="Auto generated release"; "assets" = @{ "links" = @(@{"name"="Zip", "url"=$fileUrl})}}'
    - 'wsl curl --request POST --header "Private-Token: $($env:GITLAB_API_KEY)" --data $data https://gitlab.com/api/v4/projects/7242930/releases'
  only:
    - tags